### ISSUE TITLE
Easy templating

### ISSUE THREAD

**Issue by aMarCruz** [AFASSoftware/maquette#10]
@johan-gorter are you seen [t7.js](https://github.com/trueadm/t7) ?
it's using ES6 template strings for v-node transparent generation at compilation or runtime.
it's seen very interesting for projects like maquette, minimum learning curve.

There are an example in https://github.com/trueadm/dbmonster
(integrated with [cito.js](https://github.com/joelrich/citojs), another v-node project)

**Comment by johan-gorter** [comment]
I did not yet know about ES6 template strings, so I studied them. Maquette, unlike React, does not use innerHTML, but it uses DOM methods like appendChild. Therefore, maquette never parses html. Diffing also takes place on DOM nodes and not on strings.

I cannot think of a productive way to mix ES6 template strings containing HTML and hyperscript. The hyperscript notation is really the only option for now, but I am certainly open to alternatives like jsx.

**Comment by aMarCruz** [comment]
I think that I could not explain (english is hard to me)
t7js is not generating HTML string... it is generating javascript code!
Maquette is javascript code. With this aproach, you have v-dom nodes ready to render.

**Comment by aMarCruz** [comment]
ok @johan-gorter , the example:
```javascript
var myvar = "Hello World";
var mycode = mytag`
<div class="foo">
  <p>${myvar}</p>
</div>`;
```
The browser (FF 37.x), or the transpiler (Babel, Typescript 1.5, etc), converts it to:
```
"use strict";

var _taggedTemplateLiteral = function (strings, raw) { return Object.freeze(Object.defineProperties(strings, { raw: { value: Object.freeze(raw) } })); };

var myvar = "Hello World";
var mycode = mytag(_taggedTemplateLiteral(["\n<div class=\"foo\">\n  <p>", "</p>\n</div>"], ["\n<div class=\"foo\">\n  <p>", "</p>\n</div>"]), myvar);
```
note: `mytag` is any tag used, and so is the name for the function mytag(), supplied by you in your build-time transpiler.
In my tag, do wherever you want:
```
function mytag(...){
  var code = conertToVDomNodes(arguments);
  return code;  // or writeToJavascriptModule(filename, code) ...etc
}
```
the browser do the hard work, transliteration can be happend at build time.
Easy 
:smirk:

**Comment by aMarCruz** [comment]
Take a look at t7js site, run the example in Firefox 37.x (I think Chrome Canarium cant run this), or transpile with Babel to run other browsers.

There are an example JSX to V-Dom, too, in https://github.com/Bobris/Bobril/tree/master/examples/jsx, using Babel.

If you wish your project success in the comunity, the template is the key, This is a primary must.
