### ISSUE TITLE
Website is unstable

### ISSUE THREAD

**Issue by paldepind** [AFASSoftware/maquette#11]
I often get the error message "The connection was reset" in Firefox.

**Comment by johan-gorter** [comment]
I tried reproducing your problem in Firefox, but I did not receive any error messages. Did you experience the error on the homepage or while doing the tutorial?

**Comment by paldepind** [comment]
Everywhere on the website at random. I'm talking about the kind of error where the server resets the connection and no page is displayed at all.

**Comment by johan-gorter** [comment]
The site is hosted using github-pages and I have not seen the error you are describing. I know that the tutorial uses a local version of ace-editor, which is quite large and caching is disabled using github-pages. I do want to switch to the CDN version at some point, but I doubt that this would resolve the problem you are having.

Does firebug give any extra information about the resource it was downloading (was it the main html or was it a javascript file?)

**Comment by paldepind** [comment]
> Does firebug

Nobody uses Firebug anymore ;)

I'll check in the network log if I get the error again.

**Comment by johan-gorter** [comment]
I have now rewritten the tutorial to use the CDN to get large files from. Hope this will fix all network issues once and for all.

**Comment by aMarCruz** [comment]
err... nop, tutorial is not working for me, the html frame is read-only.
Win7, 32bits with Chome 41, Firefox 37, IE 11.

**Comment by johan-gorter** [comment]
The HTML and CSS frames are readonly, because you are only supposed to edit the javascript. I intend to make a 'copy to codepen' button to make arbitrary editing possible.

If you encounter any errors, do not hesitate to report them.

**Comment by aMarCruz** [comment]
I see now, je :+1:
