### ISSUE TITLE
The API guide section of your website is broken

### ISSUE THREAD

**Issue by madlou** [AFASSoftware/maquette#135]
Direct link: https://maquettejs.org/docs/typedoc/modules/_maquette_.html

It shows the message "Not found. The specified url does not exist."

I came by the url from the following steps:

https://maquettejs.org/ > Documentation > API Documentation

**Comment by johan-gorter** [comment]
Thanks for noticing, the link is wrong, it should have been https://maquettejs.org/typedoc/index.html will be fixing it soon

**Comment by madlou** [comment]
You're very welcome, and thank you for the great tool!
