### ISSUE TITLE
Use case where VDOM and browser are out of sync

### ISSUE THREAD

**Issue by jcfranco** [AFASSoftware/maquette#139]
I've encountered this scenario where the final VDOM does not produce a change in the browser.

[Test case (instructions in comments)](https://codepen.io/jcfranco/pen/ZrbNLp?editors=0011). 

In short, the `<select>`'s render has logic that should override the user-chosen option, but the rendered `select` does not update and keeps showing the user's option as selected. 

Here's the VNode tree produced in that scenario:

```js
{
  "vnodeSelector": "select.control",
  "properties": {},
  "children": [
    {
      "vnodeSelector": "option",
      "properties": {
        "selected": true
      },
      "text": "all",
      "domNode": null
    },
    {
      "vnodeSelector": "option",
      "properties": {
        "selected": false
      },
      "text": "first",
      "domNode": null
    },
    {
      "vnodeSelector": "option",
      "properties": {
        "selected": false
      },
      "text": "second",
      "domNode": null
    }
  ],
  "domNode": null
}
```

**Comment by johan-gorter** [comment]
Hello,

Did you update the `<select>`'s `value` attribute or did you updated the `selected` attribute on the `<option>`? I think if you were to update the `<select>`'s `value` attribute, it should work ok. Otherwise, please include the `render()` function.

**Comment by johan-gorter** [comment]
I now saw the codepen link you included. The fix was to use the `<select>`'s value instead of the `selected` property, see [this codepen fork](https://codepen.io/johan-gorter/pen/vdKMNo).

**Comment by johan-gorter** [comment]
By the way, this means that a `<select multiple="true">` will never work correctly with maquette. I have not seen these on the web for a while now, so the chance that someone will need it is slim.
