### ISSUE TITLE
Projector uses `Array.prototype#find`, which is unavailable in IE10/IE11

### ISSUE THREAD

**Issue by jcfranco** [AFASSoftware/maquette#140]
Running maquette on IE10/IE11 will sometimes throw the following error:

> Object doesn't support property or method 'find'

___

Based on the **Browser support** page:

> **Polyfills**
> 
> All evergreen browsers (Edge, Chrome and Firefox) do not require polyfills,
as do IE10 and IE11.

[`projector.ts`](https://github.com/AFASSoftware/maquette/blob/master/src/projector.ts#L32) needs to avoid using `Array.prototype#find`.

**Comment by johan-gorter** [comment]
Thanks for pointing this out, fix is underway
