### ISSUE TITLE
Animating nodes during initial render

### ISSUE THREAD

**Issue by jcfranco** [AFASSoftware/maquette#143]
The animations page examples shows items (nodes) being animated **after** the initial items have been rendered. Is there a way for items to animate when rendered initially? 

&nbsp; &nbsp; &nbsp; &nbsp; **desired**&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; **actual**

![animation-on-initial-render](https://user-images.githubusercontent.com/197440/36006362-3e961c36-0cf1-11e8-9370-83265322152d.gif)

[☝️example](https://codepen.io/jcfranco/pen/ZrLoPX?editors=1011)

**Comment by johan-gorter** [comment]
There are several options for this:
- You can put your enterAnimation also on the afterCreate, like this: 
   `h('div', { enterAnimation: anim, afterCreate: anim })`
- You can put an enterAnimation function on a parentNode that does a querySelector to find the nodes to animate and run animationFunctions on them

**Comment by jcfranco** [comment]
Went with the 1st suggestion since it's simpler. Thanks!
