### ISSUE TITLE
Boolean attributes

### ISSUE THREAD

**Issue by jadeline** [AFASSoftware/maquette#145]
If I'm not mistaken, there's seems to be no way to unset a boolean attribute like `readonly`, see [jsfiddle](https://jsfiddle.net/388e8awu/4/).
Setting it to `''`, `null` or `undefined` keep the attribute with an empty value, `true` and `false` are ignored.

What about handling boolean value, `true` would set the attribute to nothing and `false` remove it ?

**Comment by johan-gorter** [comment]
The `readonly` attribute is a really confusing one. This attribute is an alias for the `readOnly` boolean property (capital O). Maquette works fine if you use the property, so the line you have to use is `h('textarea', {readOnly: readonly})` (where `readonly` is a boolean variable)

**Comment by jadeline** [comment]
I've totally missed it in the doc, my mistake, thanks for the quick answer.

**Comment by johan-gorter** [comment]
No problem, 
It is a good thing that other people can now find the answer to this common issue. 
You could use stackOverflow for questions the next time, that would make the answer visible to more people.
