### ISSUE TITLE
Error is thrown when class attribute is an empty string

### ISSUE THREAD

**Issue by jcfranco** [AFASSoftware/maquette#150]
https://github.com/AFASSoftware/maquette/issues/121#issuecomment-338957047 added the capability to change `class` between renders. Unfortunately, an error is thrown when the class is an empty string:

`Failed to execute 'add' on 'DOMTokenList': The token provided must not be empty.`

Test case: https://codepen.io/jcfranco-the-scripter/pen/OoVRzE?editors=0111

**Comment by johan-gorter** [comment]
This should fix the issue. Please tell me if you want a new release with this.

Fun fact: this makes maquette 10 bytes smaller.

**Comment by jcfranco** [comment]
> Please tell me if you want a new release with this.

Yes, please. 😄

> Fun fact: this makes maquette 10 bytes smaller.

Awesome.

**Comment by johan-gorter** [comment]
Release https://github.com/AFASSoftware/maquette/releases/tag/v3.3.1 is ready
