### ISSUE TITLE
createParentNodePath cannot find rootNode in exotic case in Safari

### ISSUE THREAD

**Issue by johan-gorter** [AFASSoftware/maquette#155]
An issue has been identified where createParentNodePath ends up not finding rootNode. The code should be made more robust to not crash.

**Comment by jspangler** [comment]
@johan-gorter was this issue resolved? We are currently having an issue where the `onmouseleave` event is triggering on a removed dom element causing an error in that method in Safari.

**Comment by johan-gorter** [comment]
This issue could not be reproduced anymore until now, so we did not resolve it.

**Comment by johan-gorter** [comment]
[Version 3.3.7](https://github.com/AFASSoftware/maquette/releases/tag/v3.3.7) should fix your problem. Can you please confirm that it did?

**Comment by jspangler** [comment]
@johan-gorter I appreciate the quick turn around. That fixed the issue! A different working solution was to remove the `onmouseleave` method and add a `mouseleave` event listener in the `afterCreate()`, but this fix is much more desirable. Thanks again.
