### ISSUE TITLE
Render root VNode as empty node when render method returns falsy value

### ISSUE THREAD

**Issue by jcfranco** [AFASSoftware/maquette#157]
I have a library of components that abstract away the VDOM and each one has a root projector. In some cases, a component may need to wait on a resource for a meaningful first render (e.g., loading locale bundle), so I'd like to return early (`undefined`) in a render method and have the projection render an empty node.

Would it be possible to enhance projections to support this? This is already supported for children, but not the root.

**Comment by johan-gorter** [comment]
I fear that the extra code needed to support this makes the maquette library way larger. A pull request indicating the change that has to be made to support this could confirm or deny this.
