### ISSUE TITLE
Support for CSS variables in `styles` property

### ISSUE THREAD

**Issue by Dyljyn** [AFASSoftware/maquette#163]
## Expected behavior

When providing a CSS variable through the `styles` property. It is added to the `style` attribute of the tag.

```js
h('div', {
  styles: {
    '--background-color': 'blue',
  }
}, [])
```

Should result in:

```html
<div style="--background-color:blue;"></div>
```

## Current behavior

CSS variables get ignored and are not rendered.

## Demo

https://stackblitz.com/edit/maquette-starter-j1rjrw?file=main.ts

**Comment by johan-gorter** [comment]
Very interesting...
It seems that this notation does work however (and is more typescript-friendly)

```ts
h('div', {
  styles: {
    backgroundColor: 'var(--background-color, gray)'
  }
}, [])
```
### DEMO
https://stackblitz.com/edit/maquette-starter-b5kdg3?file=main.ts

**Comment by johan-gorter** [comment]
A long time ago, we made a style-applyer hook to allow adding vendor prefixes. It turns out you can use to apply styles in a way that is compatible with CSS variables:

```
const projector = createProjector({
  styleApplyer: (domNode, stylename, value) => {
    domNode.style.setProperty(stylename, value);
  }
});
```

We should add this to maquette though, but this means you do not have to wait for a new release

### Demo
https://stackblitz.com/edit/maquette-starter-b5kdg3?file=main.ts

**Comment by johan-gorter** [comment]
@Dyljyn can you confirm that the patch I just committed fixes your issue and CSS variables in general? I will make a new release if it does.

**Comment by Dyljyn** [comment]
Excellent! I can confirm that your latest commit resolves it 🎉

**Comment by johan-gorter** [comment]
Release [3.4.0](https://github.com/AFASSoftware/maquette/releases/tag/v3.4.0) contains the fix.
