### ISSUE TITLE
Cannot instantiate customized built-in elements

### ISSUE THREAD

**Issue by girtsf** [AFASSoftware/maquette#181]
Hi! Thanks for the awesome library!

I've been playing around with web components (https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements) and hit a snag with maquette not instantiating customized built-in elements correctly. Looks like the `{is: "something"}` needs to be passed to `createElement` and cannot be added in afterwards.

Repro where I would expect to see two "should see this": https://jsfiddle.net/y72om3xL/1/

As far as I can tell, something like this (https://github.com/AFASSoftware/maquette/compare/master...girtsf:maquette:createelement-is?expand=1) fixes the issue. Lmk if you would like a pull request, though I'm not quite sure how to unittest it.

**Comment by johan-gorter** [comment]
Thanks for pointing this out. Is there a particular reason you want to use `h('p', {is: 'my-p'}, [])` instead of `h('my-p', {}, [])`? Both seem to have the same result.

**Comment by girtsf** [comment]
> Is there a particular reason you want to use `h('p', {is: 'my-p'}, [])` instead of `h('my-p', {}, [])`? Both seem to have the same result.

In my case I wanted to have a web component that inherits from `HTMLInputElement`, so that any properties that I add to it apply to the `<input>` element instead of me having to pass the properties down to an element in the shadow DOM. There's other ways how I could end up with the same, but this seemed convenient. I know that this is probably a weird corner case that noone else might run into. :)

**Comment by johan-gorter** [comment]
If I understand the specs correctly, if your custom-element class inherits from `HTMLInputElement`, then `h('my-input', {}, [])` should be exactly equivalent to `h('input', {is:'my-input'}), [])`. If there is a (subtle) difference, then I would certainly apply the patch to maquette.

**Comment by girtsf** [comment]
Sadly, neither `<my-input>....</my-input>` directly in HTML  nor `h('my-input')` seem to work.

[MDN](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements) in their example says:
> The element is called `word-count`, its class object is `WordCount`, and it extends the `<p>` element and, as such, it can only be constructed by setting the `is` attribute in the extended element. For example: `<p is="word-count">`, or `document.createElement("p", { is: "word-count" })`.

**Comment by johan-gorter** [comment]
That would probably indicate you forgot to call [customElements.define](https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/define)

**Comment by girtsf** [comment]
> That would probably indicate you forgot to call [customElements.define](https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/define)

That's the expected behavior though: `<my-input>` does not work (and should not work for customized built-in elements), while `<input is="my-input">` works as expected:  https://jsfiddle.net/tb4jykqu/1/

**Comment by girtsf** [comment]
Thank you!
