### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by maxxxxxdlp** [AFASSoftware/maquette#183]
Just a FYI on a few broken links I found in the documentation:

On https://maquettejs.org/typedoc/functions/createMapping.html the "with arrays" link is broken.

On https://maquettejs.org/tutorial/12-done.html, the "Finish the remote in our bonus level and learn about components" link is broken.

The first example in https://maquettejs.org/docs/server-communication.html is broken

![Screenshot 2023-06-30 at 19 36 25](https://github.com/AFASSoftware/maquette/assets/40512816/70a8d7c1-c1c8-46a0-b031-cbd79bc54b09)

**Comment by johan-gorter** [comment]
Thank you for reporting. I think I found and fixed the problems you found. They were mostly caused by upgrading our website tooling.
