### ISSUE TITLE
Vdom html content

### ISSUE THREAD

**Issue by HelloZeroNet** [AFASSoftware/maquette#20]
How can I add pre-rendered html to vdom?

Thanks!

**Comment by RickHoving** [comment]
You can add pre-rendered html using the afterCreate property.
Then after the vNode is rendered it will feed the actual domNode to the function as a first parameter.
There you can use the innerHTML property to insert your pre-rendered html.

You can see a working demo here: http://codepen.io/rhoving/pen/MaRYRe 
Or look at the code below:

```javascript
document.addEventListener('DOMContentLoaded', function () {
  var h = maquette.h;
  var domNode = document.body;
  var projector = maquette.createProjector();
  
  var prerenderedHTML = "<input type='text'>";
  var afterCreateFunction = function(node){
    node.innerHTML = prerenderedHTML;
  };
// This function uses the 'hyperscript' notation to create the virtual DOM. 
// The 'you' variable is used twice here
function renderMaquette() {
  return h('div', {
    afterCreate: afterCreateFunction 
  });
}
  
projector.append(domNode, renderMaquette);

});
```

**Comment by HelloZeroNet** [comment]
Thanks, works perfectly! :)
(Btw there is a small error at http://maquettejs.org/docs/jsdoc/module-maquette.html#.h the last parameters probably afterUpdate instad of afterCreate)

**Comment by HelloZeroNet** [comment]
Any suggestions how to handle data changes on html content?

I added the render function to afterUpdate, but it's called even if node is not modified, so currently I save the content of body (the content i want to display as html) when the afterUpdate function called and only re-render it (using markdown) when `body != lastcalled_body`

Is there any way to query node change time or any prettier solution?

**Comment by RickHoving** [comment]
Could you please provide with the use case you are using maquette for?
That will help me better understand the problems you're experiencing.

Maquette fires the afterUpdate function to all elements which have a afterUpdate property after it is done updating the dom.
You can use this function to react to this.

You could (mis)use the updateAnimation function for your purpose like in this example:
```javascript
document.addEventListener('DOMContentLoaded', function () {
  var h = maquette.h;
  var domNode = document.body;
  var projector = maquette.createProjector();
  
  var afterUpdateFunction= function(elem, properties, previousProperties){
    if(properties.classes.disabled && !previousProperties.classes.disabled){
      console.log("its disabled");
    } else if(properties.classes.enabled && !previousProperties.classes.enabled){
      console.log("its enabled");
    }
  };
  var toggleEnabled = function(){
    classEnabled = !classEnabled;
  }
  
  var classEnabled = false;
  
  function renderMaquette() {
    return h('div', {
      classes: {
        'enabled': classEnabled,
        'disabled': !classEnabled 
      },
      updateAnimation: afterUpdateFunction 
    }, [
      h('input', {
        type: 'button',
        value: 'toggle class',
        onclick: toggleEnabled
      })
    ]);
  }
  
  projector.append(domNode, renderMaquette);
 
});```

In the updateAnimation you get a reference to the actual element, the properties the vnode has after the update and the properties the vnode had before the update.
With specific classes, you can compare the before and after to see whether this node has actually been changed.

**Comment by HelloZeroNet** [comment]
If I click to any of the items all of them will be re-rendered:
http://codepen.io/anon/pen/LpvpXN?editors=001

**Comment by HelloZeroNet** [comment]
Thanks, the updateAnimation method works: http://codepen.io/anon/pen/QjPGGN?editors=001

I had to change

```coffeescript
    h("div", {
      "onclick": @handleClick, 
      "afterCreate": @renderBody, 
      "afterUpdate": @renderBody
    }, [@body])
```

to
```coffeescript
    h("div", {
      "onclick": @handleClick, 
      "value": @body,
      "updateAnimation": @renderBody,
      "afterCreate": @renderBody
    })
```

The updateAnimation seems not firing if the text content of the node updated. I think according to docs it should: "updateAnimation: The animation to perform when the properties of this node change. This also includes attributes, styles, css classes. This callback is also invoked when node contains only text and that text changes."

But thanks for the answer, this is exactly what I wanted.

**Comment by johan-gorter** [comment]
Hello @HelloZeroNet, I corrected the documentation typo you found. Also about the updateAnimation callback that did not fire: this was acutally a bug. The 2.1.5 release contains the fix.

By the way: cool to see how maquette can be used from coffeescript!
