### ISSUE TITLE
Exit / Enter anim triggered on reordering

### ISSUE THREAD

**Issue by HelloZeroNet** [AFASSoftware/maquette#21]
I want to create real-time update list of threads, the enter/exitAnimation works well when new comes in or old removed, but if one of the threads position changed then it fades off/fades in every other element in the list:

http://codepen.io/anon/pen/GpbYzz?editors=001 (by clicking on an element its moves to top in the list)

I don't expect animated position change (but would be nice), fade out from old position and fade in to new position could do.

Is there any easy way to solve this?

**Comment by johan-gorter** [comment]
First of all, let me tell you what is going on: 

One element is moved up, but the algorithm used by maquette sees this as if the elements above the element are removed and new elements are re-added below the element.

Reordering is difficult to do right, but it is definitely possible to do. An example how this can be done is shown here: http://johan-gorter.github.io/maquette-demo-hero/

If you want to do a different animation when moving items, I recommend the following:
- Use a boolean flag 'moving' and set it to false
- When someone does the move-to-top, set the 'moving' flag to true
- In the enter/exitanimation functions, check the 'moving' flag and act accordingly (return immediately to keep things simple)
- In an afterUpdate of the parent div, reset the 'moving' flag to false

**Comment by HelloZeroNet** [comment]
Thanks for the suggestions, changing the item's key attribute on click also fixes the problem (and avoids all item re-creation)

Combining key change + your flag usage suggestion I was able to create animated reordering: http://codepen.io/anon/pen/BogvzZ?editors=001 (tested in chrome)

 - Saves item position on click
 - Modifies key attribute
 - On new item's afterCreate places it to of old item Y position (using TranslateY)
 - Animates back TranslateY 0px
