### ISSUE TITLE
Is it possible to use maquette with other doms?

### ISSUE THREAD

**Issue by user471** [AFASSoftware/maquette#25]
For example, libraries like pixi.js, three.js, nativescript have their own dom. 
Or is it only support html?

**Comment by johan-gorter** [comment]
Hello,

Unfortunately, Maquette does not currently support other DOMs. We are trying to keep maquette lightweight, so adding other DOMs is not really an option for us. There are however some ways you could try to integrate other DOMs:

- Make the other DOM compatible with normal DOM, which means the other DOM nodes should at least provide setAttribute, appendChild, removeChild and insertBefore methods. If needed, you could alter the prototype of the other DOM nodes to provide these methods
- Make your own DOM methods and Projector. Which means you are effectively rewriting 2/3rd of maquette. You would basically only be using maquette's h() method
- Make a fork of maquette for the other DOM

Hope this answers your question.
