### ISSUE TITLE
Routing [enhancement]

### ISSUE THREAD

**Issue by sqram** [AFASSoftware/maquette#26]
Nearly all SPAs today require front end routing.
Mithril does a good job at implementing it while still keeping the library small.
Perhaps there should be a version of Maquette with routing, or, an example of how to use it with a routing library.

**Comment by johan-gorter** [comment]
First of all, maquette was created with the philosophy of 'Do One Thing and Do It Well' in mind. This is why maquette only handles the DOM. You should consider it to be a library and not a framework.

Having said this, I agree that not being a framework makes maquette harder to get started with. It should be easy to create a lightweight framework based on maquette that solves the common single-page-app needs. At @AFASSoftware, we are currently building a  very versatile framework that can navigate between thousands of different pages, so a lightweight framework does not work for us. More information on the framework we are creating can be found [here](https://dev.afas.nl/1337/de-frontend-van-profit-next) (in dutch).

I think that a lightweight framework should include the following aspects:

 - Routing (using the #)
 - Loading new pages on-demand
 - Promise based communication using XMLHttpRequest (using [axios](https://github.com/mzabriskie/axios) for example)
 - Polyfills for IE and old safari versions
 - Be very small to download, and fast to start, so there is no need to for isomorphic server logic

Finally, the TodoMVC example that is included with maquette shows one way to make a [router by using a component](https://github.com/AFASSoftware/maquette/blob/master/examples/todomvc/js/components/todoRouter.js).

I will be keeping this issue open to see if we can get some more input on the idea of such a framework, or even contributers.

**Comment by veerdhakad** [comment]
fg
