### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by HelloZeroNet** [AFASSoftware/maquette#28]
Is there list of changes between versions?

**Comment by johan-gorter** [comment]
I try to post a news-item on the maquette-website and on medium every time I make a release. I am still busy writing the one for the 2.2 version. A sneak preview: Switched to Typescript, 100% test coverage and it is now possible to write code using the JSX notation using Babel.

**Comment by timohofmeijer** [comment]
JSX! :+1:

**Comment by johan-gorter** [comment]
By the way, we consider maquette to be feature-complete right now, so the list of changes will not be very long. If we were to make a breaking API change, we will be doing a major version upgrade of course.
