### ISSUE TITLE
Event handler parameter passing

### ISSUE THREAD

**Issue by HelloZeroNet** [AFASSoftware/maquette#29]
What's the best way to pass an extra argument to the event handler?

Maquette does not allow anon functions. In an another framework (snabdom) I have seen something similar to this:
```javascript
function handleClick(message) {
  alert(message)
}

function render() {
  return h("div", [
    h("a", {"onclick": [handleClick, "Hello from Item 1!"]}, "Item 1"),
    h("a", {"onclick": [handleClick, "Hello from Item 2!"]}, "Item 2")
  ])
```

Ps: Thanks for the library, we are big fan on Maquete. Just finished the second site, everything worked well (the only thing missed is dom-reordering support): [Distributed messaging site](http://i.imgur.com/ypgRC2H.png), [Homepage and newsfeed of the network](http://i.imgur.com/H60OAHY.png)

**Comment by johan-gorter** [comment]
The best way to do this is to put a custom attribute on the item that is clicked. In the event handler, you can do evt.target.getAttribute() to read the value. We usually prefix the attribute with "data-" as a convention, but this is not required.

By the way, a VNode-property will only become an attribute if its value is a string. Other type of values will become properties and can be read using evt.target[]
