### ISSUE TITLE
Tutorial finale maxes CPU

### ISSUE THREAD

**Issue by ryascl** [AFASSoftware/maquette#30]
The tutorial finale at http://maquettejs.org/tutorial/14-finale.html maxes one of my CPU cores when I start interacting with the UI. I didn't alter the tutorial code.

**Comment by johan-gorter** [comment]
This is due to the animated lights from the UFO. It is just cosmetic and it has nothing to do with maquette itself.

We will run some experiments with tuning down the visual effects, to make the tutorial more battery-friendly.

Thanks for bringing this to our attention.

**Comment by johan-gorter** [comment]
The animation now stops after a few seconds. This should stop laptops from getting hot and prevent batteries from draining.
