### ISSUE TITLE
Preventing rerendering sometimes in event handlers?

### ISSUE THREAD

**Issue by pdfernhout** [AFASSoftware/maquette#31]
Sometimes you know that a rerender is not needed after an event handler runs. A common use case involves keyboard events like onkeydown in a widget where you can ignore them unless a specific key is pressed (like the Enter key). Another use case is for mouse events like onmouseenter where only occasionally you might to change the GUI like with a popup for a specific element in big grid (perhaps only after the user has dwelled over a location for some time like if they are quickly moving the mouse across a grid). Potentially, moving the mouse quickly across a grid could otherwise generate dozens of spurious rerenders per second. So, what is the recommended way to prevent rerendering by Maquette once an event handler has been called?

It seems to me one possible option with Maquette currently would be to create a new eventHandlerInterceptor function for a projector that perhaps checks a global flag set before the event handler us called. Would that be the recommended approach? It seems a little ad-hoc to me though for what may be a common use case. Still, that might be the best for perfomance if most users don't need this. If so, it might be worth providing an example of doing that in the cookbook section of the documentation.

Right now, by default, it seems like Maquette commits to a rerender before the event handler code is called -- perhaps to avoid the overhead of a try/finally? And projectors can have rendering stopped and resumed, but as I read the code, have no function to unschedule a render (not saying they necessarily should). So, it does not seem to me this can be done without setting a new eventHandlerInterceptor for a projector.

Here is how Mithril does that, also involving a global variable, but there might be better ways  (perhaps even involving using the event itself somehow) -- and Mithril's approach runs the risk of breaking the rerendering process by a missing endComputation call like in an exception handler:
https://lhorie.github.io/mithril/mithril.redraw.html

In any case, thanks for the great library. I'm having fun playing with it. :-)

**Comment by johan-gorter** [comment]
Hello, we simply never worry about superfluous rerenders. As long as they are fast enough, which they should be, the user wouldn't notice that extra rerender.

If you really want to be able to skip rerendering you can always create your own projector implementation. (And maybe open-source it)

**Comment by pdfernhout** [comment]
@johan-gorter Thanks for the reply. And a big advantage of Maquette being focused and well-written (and in TypeScript) is that it would be straightforward to make a new project implementation if supplying  a new eventHandlerInterceptor was not good enough. :-) I'm impressed with how clearly written and well factored the Maquette  code is. And I can see the value in not cluttering up the codebase with non-essential special cases.

As I mentioned previously elsewhere (dojo/meta issue eleven), computational efficiency does affect garbage collection demand and also battery life on mobile, so there are also sometimes other factors to consider even when things render fast enough. I'll let you know if I try an experiment related to that. For now, it is just a hypothetical issue.

**Comment by johan-gorter** [comment]
Hello @pdfernhout, I am very curious about your findings about the real impact on battery life and garbage collection. I have not run many experiments with that, mainly because at @AFASSoftware we are focusing on modern devices only. I am especially curious about the differences from the [incremental-dom](/google/incremental-dom) approach.

**Comment by pdfernhout** [comment]
I created pull request #37 because it seems like you could not actually override eventHandlerInterceptor even if you wanted to. Beyond making re-rendering optional with a new eventHandlerInterceptor, you might also want to change how the event handlers were called like by setting "this" and/or by supporting arguments for event handler functions as discussed in issue #35. So, these three issues are all related in that sense.
