### ISSUE TITLE
Support for IE9

### ISSUE THREAD

**Issue by kitsonk** [AFASSoftware/maquette#33]
I can't seem to find where you explicitly indicate browser support, but I have noticed that you cannot currently support IE9 due to the `scheduleRender()` utilising `requestAnimationFrame` for providing rendering.

Have you considered supporting some of the older browsers (specifically IE9)?

**Comment by HelloZeroNet** [comment]
Polyfill for IE9 & iOS6:
https://github.com/AFASSoftware/maquette/blob/master/src/maquette-polyfills.js

**Comment by kitsonk** [comment]
Thank you!

Suggestion for the Maquette maintainers to add that to the documentation somewhere.  It isn't mentioned in the README or anywhere on maquettejs.org.

**Comment by johan-gorter** [comment]
I agree we should document the browsers that maquette supports. We will keep this issue open until we have done this.

Short summary: 

- Evergreen browsers (chrome, firefox and edge) and IE10+, Safari 7+ work out of the box.
- IE9 and IOS6 Need the polyfill mentioned
- IE7 and IE8: We have polyfills for these as well, we will integrate these in the polyfills soon

There is also one other thing we should mention. The very convenient `input` event is not available in IE7 and IE8 and it is [buggy in IE9](http://benalpert.com/2013/06/18/a-near-perfect-oninput-shim-for-ie-8-and-9.html). I recommend using onkeyup if you need to support these browsers.

**Comment by johan-gorter** [comment]
Browser support is now documented here: http://maquettejs.org/docs/browser-support.html
