### ISSUE TITLE
npm install warnings

### ISSUE THREAD

**Issue by pdfernhout** [AFASSoftware/maquette#36]
Here are some warnings from doing an install today. Should any of these npm packages that Maquette depends on be updated?

maquette$ npm install
npm WARN deprecated tsd@0.6.5: TSD is deprecated in favor of Typings (https://github.com/typings/typings) - see https://github.com/DefinitelyTyped/tsd/issues/269 for more information
npm WARN deprecated mocha-jsdom@1.0.0: Consider jsdom-global instead. https://www.npmjs.com/package/jsdom-global
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated lodash@1.2.1: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
WARN engine joi-assert@0.0.3: wanted: {"node":">= 0.10.0 <= 0.11.0"} (current: {"node":"4.3.0","npm":"2.14.12"})
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.

**Comment by jvanoostveen** [comment]
Not so sure about the `typings` yet, it still gets most definitions from the `tsd` repository and uses a different structure. I was hoping for more libraries to include the `d.ts` within the library itself, but that doesn't seem to be the case very soon.
Not sure if all warnings can be removed by updating, as some of them are dependencies of dependencies. Most others are drop-in replacements so I'll start with those :smile:.

**Comment by jvanoostveen** [comment]
Except for TSD / Typings, the warnings come from dependencies of dependencies...
