### ISSUE TITLE
Certain Array Mutations Inefficient

### ISSUE THREAD

**Issue by kitsonk** [AFASSoftware/maquette#50]
_Context: We have been prototype using Maquette with [dgrid](https://dgrid.io) considering using it for the next major version.  We have found a few things that we see as challenges for us in adopting it. @kfranqueiro, @maier49, and @edhager have been working on the prototyping._
## Problem Description

Certain VDOM array mutations appear to be inefficient.  Specifically given an array of VNodes: `[ A, B, C, D, E ]` and moving `E` to before, example `B` causes `B`, `C` and `D` to be touched.

@kfranqueiro wrote a [CodePen](http://codepen.io/kfranqueiro/pen/LNBjGM) that demonstrates the issue.  It highlights any nodes that are "touched" during the DOM modifications.  If you move an item up the array order (e.g. from index 9 to 1) or if you click the `Move last item to top` button.
## Impact

Why we are concerned about this is that dgrid is often used in situations where thousands of rows might be rendered on screen of a virtual data set of millions of records.  We virtually page rows in and out of memory and also render them at different points.  Mutations to the order of the rows can occur via many different mechanisms, including user input, server side updates sent to the client, or application logic.  We therefore care greatly about any inefficiency in the mutations of lists.
## Discussion

There maybe an obvious improvement to the mutation detection algorithm.

An the other hand, as we discussed with our wider team, we acknowledged that any change detection algorithm is likely to have some sort of inefficiency.  One thought we had, is that if in the properties of the VNode which has an array of children, to provide an optional _hint_ around the type of mutation performed.  Maquette could then use that information to more efficiently detect any mutations.  We haven't thought through the details of what this _hinting_ might look like, but it seems like it could be an effective way of making Maquette even more efficient.

**Comment by HelloZeroNet** [comment]
I also met this problem: https://github.com/AFASSoftware/maquette/issues/21

There is a possible workaround if you modify the node's key (eg. by appending a character to it) it will be remove and a new one will be created. 
Demo: http://codepen.io/anon/pen/BogvzZ?editors=001 (By clicking on an item it will move to top)
But this is hackish, I have never used in production and a  proper solution (moving the modified node instead re-creating) would be really nice.

**Comment by johan-gorter** [comment]
Hello,

At @AFASSoftware, we are also using large lists and I hope to get around to blogging about it in the near future. An interesting detail about our implementation is that we were able to use both a sticky header and sticky columns.

In our list implementation we made sure that we are only rendering the cells that are currently within the viewport. The cells outside the viewport are removed from the DOM. This way we can scroll an almost infinite list. (we also render some extra rows depending on the scrolling speed and direction)

When using lists consisting of thousands or millions of rows, I would suggest trying to do the same thing, so only 10 to 100 rows are rendered in the DOM. This will not only make the VDOM mutations less painful, it will also make the UI more responsive. We are very enthusiastic about this approach.

Another technique you can also use is to use a `key` on the `VNode` that consists of both the database-id and the revision-number (used in optimistic locking). This way maquette will never re-insert untouched database-records.

I am also curious about ways maquette can make smarter mutations. If this algorithm is not too costly (in terms of performance and lines of code) we would consider adopting it in maquette.

**Comment by kitsonk** [comment]
> Another technique you can also use is to use a key on the VNode that consists of both the database-id and the revision-number (used in optimistic locking). This way maquette will never re-insert untouched database-records.

The referenced codepen utilises an `key` property.  We think we still saw, when moving a "row" from lower in the list to higher affect the "untouched" rows higher up, even though the key was consistent.  Other mutations didn't seem to exhibit that behaviour.

**Comment by pottedmeat** [comment]
In `updateChildren`, if `findIndexOfChild` finds the first child encountered at the last position in the array of old children, `oldIndex` gets set to an out-of-bounds number and, from then on, the branch of code that reads `// New child` will be used and `createDom` will be called for each.
