### ISSUE TITLE
Event Delegation

### ISSUE THREAD

**Issue by kitsonk** [AFASSoftware/maquette#52]
*Context: We have been prototype using Maquette with [dgrid](https://dgrid.io) considering using it for the next major version.  We have found a few things that we see as challenges for us in adopting it. @kfranqueiro, @maier49, and @edhager have been working on the prototyping.*

## Problem Description

First, apologies, that this might be more of a support item than an issue with Maquette, but since this was part of the challenges with our prototype, I figured I would bring it up here.

There appears to be no easy way of utilising event delegation with Maquette.  For example, if I have a `<div>` that contains 10 `<button>` elements, I might want to put a listener on the `<div>` and allow event bubbling to occur when the `<button>` is clicked to actually handle the event.  In a situation where the application directly manipulates the DOM, it would be able to determine what action to take because it placed each of the DOM nodes and knows what part of the DOM relates to the application logic.

In a VDOM situation, not knowing about the DOM is most compelling advantage.

## Impact

The specific impact to dgrid is that, with thousands of rows, it is often easier to put a listener higher up the DOM and allow event bubbling to occur, meaning one listeners needs to be attached and can manage thousands of different scenarios.  In order to go to a 1:1 mapping of VNode to listener would be a significant amount of refactoring.

Outside of that, we see that the general use case of being able to harness the power of event delegation and bubbling in a way the integrates well with Maquette as a compelling feature.

## Discussion

We might be missing something around the intent of Maquette and are "doing something wrong" and there is already a reasonable solution.

Outside of that, we think there might be two approaches to solving this use case:

* Listeners could hold references to VDom generated and then walk the VDom looking for matching DOM nodes that have been added to the VDom.  This seems like a lot of work and likely would not be efficient.
* Maquette could potentially intercept DOM events and decorate them in some fashion (e.g. either decorate the DOM event with a reference to the VDom node or only decorate the event if the `key` property was supplied in the original VNode)

**Comment by johan-gorter** [comment]
Event delegation is a technique that we also use at @AFASSoftware. It is actually not as hard as you might think. When rendering the VDOM you can put custom properties like `{'data-id': ''+id}` on the `VNode`-s, which create an attribute on the real DOM. When handling an event, you can use the `event.target` to figure out the DOM node that was clicked and navigate to its parentNode until you find a node that has the `.getAttribute('data-id')`.

This may not be the easiest solution, but I think it is more transparent than having maquette do the delegation for you.

**Comment by kitsonk** [comment]
I thought we might be missing something.  We will take a look at trying something like that.
