### ISSUE TITLE
Allowing DOM Elements as part of VDOM

### ISSUE THREAD

**Issue by kitsonk** [AFASSoftware/maquette#53]
Sorry to be overly verbose today, but another part of team (@pottedmeat) and I were discussing another use case we will likely encounter.

As we transition to a virtual DOM, it maybe challenging to have all components move to a virtual DOM.  While a Projector can manage just a portion of the DOM, allowing other code to perform as normal, if we wanted to contain a "legacy" component in the VDom, we don't see a way we could do that at the moment.

One solution we thought of, would be to allow a VNode children to contain a Element in the array and Maquette place that Element appropriately in the DOM with no further styling.  We would create Elements for our legacy components and instantiate them, passing them back as part of the render response.  Again, we may simply be missing a solution.

**Comment by RickHoving** [comment]
Hi,

Did you consider using the afterCreate event to attach your legacy elements to the DOM?

Kind regards,

**Comment by kitsonk** [comment]
@RickHoving thank you!  That would work perfectly, essentially provide an `afterCreate` for the VNode "wrapper" for our legacy components and then attach them there.
