### ISSUE TITLE
Querying Virtual DOM elements using a css selector?

### ISSUE THREAD

**Issue by tusharmath** [AFASSoftware/maquette#57]
```js
const vTree = h('div.landscape', [
  h('div.saucer', {style: `transform:translate(${x}px, ${y}px)`})
])

// and then search as —
maquette.find(vTree, 'div.saucer')
```

**Comment by johan-gorter** [comment]
Hello,

Querying a virtual DOM is normally only needed when doing unit testing. We created the project `maquette-query` for this.

This project is still in pre-release and we welcome contributions. The selector may currently only contain one part (`div` or `.saucer`) in your example.

What is your use-case for querying?

**Comment by tusharmath** [comment]
I am building a DOM driver for [cycle](http://cycle.js.org). The API looks as follow —

```js

const click$ = DOM.select('.saucer').events('click')
```

Here `click$` represents an [Observable](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/observable.md) which emits the click event everytime the element is clicked upon.

**Comment by johan-gorter** [comment]
I think it would be easier if you used the `afterCreate` handler. This callback is meant to facilitate integration with other libraries. This function gets called with the DOM node that was created, so there is no find it using a query anymore. Good luck!

**Comment by tusharmath** [comment]
Its not documented here though — http://maquettejs.org/docs/typedoc/modules/_maquette_.html

**Comment by johan-gorter** [comment]
http://maquettejs.org/docs/typedoc/interfaces/_maquette_.vnodeproperties.html#aftercreate
