### ISSUE TITLE
Error in "Working with arrays" sample

### ISSUE THREAD

**Issue by jcfranco** [AFASSoftware/maquette#69]
The last sample from [Working with arrays](http://maquettejs.org/docs/arrays.html) has an error that prevents it from rendering properly:

The last line 

```js
maquette.createProjector(domNode, renderMaquette);
```

should be

```js
projector.append(domNode, renderMaquette);
```

Working demo: http://codepen.io/anon/pen/kXqwRY

**Comment by johan-gorter** [comment]
Thanks for reporting it!
