### ISSUE TITLE
Communication between components

### ISSUE THREAD

**Issue by sprat** [AFASSoftware/maquette#71]
Imagine I have a Menu sub-component used in an Application component: the Application instance would like to know when a menu item is selected in the Menu instance in order to swap the main content displayed in the application (for example). In other words, I need a way to communicate between a child component and its parent component. How can this be achieved in Maquette?

Sure, I can pass a callback owned by the application instance to the menu instance, which will be called when an item is selected. But I'm a bit reluctant to do that because the "selection" event is just a "rendering-side" aspect of the menu component, so I would prefer the event not to leak into my Menu object API, but to stay inside the render function/method instead.

So, I would like to deal with events at the "rendering-side". But I guess it means I have to send a CustomEvent from the Menu's render function and register a CustomEvent handler inside the Application's render function, right? Is this use-case supported in maquette?  Are there other alternatives to CustomEvent for my use-case?

PS: I'm new to maquette and I really like the API. Good job!

**Comment by johan-gorter** [comment]
Hello,

What we usually do is pass callbacks to components that get invoked when items get clicked. A Menu could receive a callback `menuItemClicked(menuItem: MenuItem)` for example. Imho this does not leak any application-specific knowledge into the menu/menuitem. The owner of the menu could do anything like routing or changing a variable.

An event system is also certainly possible. I do not recommend using the DOM hierarchy to bubble the events though. I can imagine the Application creating the menu using `menu = createMenu(...)` and afterwards calling `menu.addEventListener('itemClicked', navigate)` or something.

**Comment by johan-gorter** [comment]
If you have any more questions, please use StackOverflow, so more people can respond to your question. Thanks!

**Comment by sprat** [comment]
Done: http://stackoverflow.com/questions/39589973/communication-between-components-in-maquette

Can you please repost your answer on stackoverflow so that I can make some comments?

**Comment by johan-gorter** [comment]
Done
