### ISSUE TITLE
Elements using CSS Animations are not removed from the DOM on completing the exit animation

### ISSUE THREAD

**Issue by agubler** [AFASSoftware/maquette#73]
Elements using CSS Animations rather than CSS Transitions are not being removed from the DOM on completion of an exit animation.

This is because the provided `css-transitions.js` javascript is only listening on the `transitionend` event and not also the `animationend` event.

**Comment by RickHoving** [comment]
I created [this](https://github.com/AFASSoftware/maquette/pull/74) pull request according to your description. After a review by @johan-gorter  we can include this. Or just pick the file and try if this solves your problem :)

**Comment by agubler** [comment]
Thanks effectively what I did locally to get animations to correctly remove the element from the DOM :-) I just made the end events an array and iterated through them instead of explicitly declaring another variable.

Another question, is there any reason why this isn't a typescript module that we could import instead of load onto window?

**Comment by johan-gorter** [comment]
Hello, the reason for the css transitions not being Typescript is because we switched to Velocity before we switched to Typescript. Rewriting this bit to Typescript has not gotten any attention thisfar.
