### ISSUE TITLE
Feature request: support undefined values for the class attribute 

### ISSUE THREAD

**Issue by sprat** [AFASSoftware/maquette#77]
Hello,

I'm using webpack and CSS modules in my `maquette.js` application and I am a little bit annoyed because `maquette.js` does not accept `undefined` values for the `class` attribute.

For example, I often do that in my code:

``` javascript
var styles = require('./component.css');

function renderMaquette() {
  return h('div', { class: styles.root }, 'blah blah');
}
```

When we use CSS modules but we don't have the corresponding `.root` rule in the CSS, `styles.root` returns `undefined` which causes `maquette.js` to throw an error because the class value is not a string.

I often do this mistake when refactoring my components and their CSS files and it's quite hard to find where the mistake is once you've done it. So, can I suggest supporting `undefined` values for the `class` attribute as a synonym for the empty string?

Side note: I would also like to pass an array of classes to the `class` or `classes` attributes but it's not supported either. In those cases, I use the `classnames` library to format the `class` attribute, and I think it would probably be a good idea to delegate the `class` handling to this library in `maquette.js`.

**Comment by johan-gorter** [comment]
Hello,

Just to be curious, when passing `undefined` to the `class` attribute, there is obviously something wrong with the code. The easiest way to spot this error imho would be if the debugger would break at exactly that point so you can fix the problem immediately.

If maquette would be lenient and accept undefined as you suggest, would the error not be way harder to spot? A missing css class would not be as obvious as a crash.

Would the following replacement for the `h` method maybe help you spot the error earlier? 

```
  let h = function() {
    let result = maquette.h.apply(undefined, arguments);
    if (result.properties && result.properties.hasOwnProperty('class') && !result.properties.class) {
      throw new Error('undefined was passed as value to class');
    }
    return result;
  }
```

**Comment by sprat** [comment]
As I explained, when we use CSS modules, the object returned by CSS `require` call contain only the classes which exist in the CSS file. So imagine that I had a `myClass` class in my CSS before, but I remove it after a refactoring: `styles.myClass` now returns `undefined`.

I can probably go with your suggestion and use a custom `h` function.

But, I think it would be really convenient to allow `undefined`/empty values for `class`. In fact, I don't consider that it's a programming error to use a class that does not always exist in the CSS. In that case, I don't want any class attribute, even if I passed a class attribute evaluating to `undefined`/empty.

**Comment by johan-gorter** [comment]
Hello,

Could you please provide some code samples that would benefit from this? We experimented with CSS modules ourselves, and we not only used the `class` attribute, but also the keys from `classes`. This last scenario would not be fixed by just one extra if-statement.

**Comment by sprat** [comment]
As I said, I actually use the `classnames` library to deal with classes, as it accepts `undefined` values and allows combining many classes (eventually `undefined`). For example, I actually write code like this:

```javascript
var classNames = require('classnames');
var Login = require('./login');
var styles = require('./dashboard.css');
var contours = require('./contours.css');

function Dashboard(title, loginUrl) {
    var content = Login(loginUrl);

    // code changing content now shown here...

    function render(h) {
        return h('div', { class: classNames(styles.dashboard) }, [
            h('div', { class: classNames(contours.VNT, styles.dashboardTitle) }, title),
            h('div', { class: classNames(contours.TV, styles.dashboardContent) }, content.render(h))
        ]);
    }

    return {
        render: render
    };
}
```

But I'd like to write the `render` function like this instead:
```javascript
    function render(h) {
        return h('div', { class: styles.dashboard }, [
            h('div', { class: [contours.VNT, styles.dashboardTitle] }, title),
            h('div', { class: [contours.TV, styles.dashboardContent] }, content.render(h))
        ]);
    }
```

As you said, I can use a custom hyperscript function to deal with that, that's what I'm going to do now.

In fact, I think you designed your hyperscript function to reflect the DOM API, more or less. On the contrary, I see the hyperscript function as an efficient/easy way to write HTML, so I'd like some shortcuts to make it easier to write working view code.

Maybe your philosophy is to keep maquette low-level/simple and let users write their own custom hyperscript function. In that case, it's perfectly fine for me.

But note that the `classes` attribute you introduced seems to be an attempt to add a user-friendly API to deal with `class`. To me, the `class` attribute should probably accept strings, undefined, lists, objects, like classnames does, so that it's easier for the developer, and there would be no need for `classes`. Or, if you want to keep maquette low-level/simple, the `classes` attribute should probably not be implemented in maquette at all: the users can use their own hyperscript functions after all.

**Comment by johan-gorter** [comment]
Hello,

The `classes` property is meant for classes that are added/removed dynamically. Maquette uses the `classList` property of an `Element` to do this efficiently. When we were experimenting with css modules, we used the following construct to add/remove classes dynamically:

```typescript
h('div', {classes: {[styles.first]: index===0, [styles.last]: index === length - 1}}
```

This would crash if `first` or `last` is missing from the stylesheet. Is that allright with you?

**Comment by RickHoving** [comment]
@sprat We want to address using the class attribute in [Maquette 3.0](https://dev.afas.nl/blog-dev/ideas-for-maquette-3) and would love your imput on this.
You can continue this discussion at #121
