### ISSUE TITLE
numeric values in props

### ISSUE THREAD

**Issue by katywings** [AFASSoftware/maquette#79]
Hey hey

I just saw, that `h('div',{'data-id':56},'fubar')`, will result in `<div>fubar</div>`

http://codepen.io/katywings/pen/vXbVdR

---

The data attribute is not rendered. I think it would be better to output `<div data-id="56"...`

Is it intended to ignore numeric values? My current workaround is to cast the number to string `h('div',{'data-id':'' + 56},'fubar')`

If its not intended from your side I would fix the problem and create a pull request ;).

Toodaloo
Katja :)

**Comment by RickHoving** [comment]
You are correct, Maquette indeed handles string values and other value types different. 
A string value is rendered as a attribute which you see in the dom as you stated.
A different value type like a number is added to the element as a property not an attribute.

I've altered your codepen to demonstrate how to obtain both value types: [http://codepen.io/anon/pen/gwqQxV](http://codepen.io/anon/pen/gwqQxV )

**Comment by RickHoving** [comment]
As a side-note, you can also ask questions about Maquette on stackoverflow. This makes the questions easier to find for other developers.

**Comment by katywings** [comment]
Hey Rick

Thx for the info and the example :+1: Yeah this behaviour makes sense ^^. 

Indeed, Stackoverflow is cool for questions - but because I felt really sure, that it was a Bug / Feature Request I wanted to contact you directly and not via some "behind the music - ish- place" ;)
