### ISSUE TITLE
More robust error handling/detection...

### ISSUE THREAD

**Issue by kitsonk** [AFASSoftware/maquette#80]
We are trying to isolate a transitory error that is isolated to Android 4.4 under certain conditions.  While we aren't a 100% certain what is occurring, we believe there is an issue that is occurring during a render.  Because it is difficult to recreate the issue in a scenario where we can actually access the console log, it is becoming difficult to further isolate the issue.

Also, when a render throws, the projector will essentially never render again, no matter what and there appears to be no way of "resetting" the projector (or interrogating what might have occurred).  Because renders are called async, there is no (easy) way to "try ... catch" and provide some error handling or instrumentation.

The [following lines](https://github.com/AFASSoftware/maquette/blob/be6eefc9c9121f2df689288a672f438915af55c8/src/maquette.ts#L1159-L1167) from `maquette.ts` are relevant:

```ts
if (!renderCompleted) {
  return; // The last render threw an error, it should be logged in the browser console.
}
renderCompleted = false;
for (let i = 0; i < projections.length; i++) {
  let updatedVnode = renderFunctions[i]();
  projections[i].update(updatedVnode);
}
renderCompleted = true;
```

Possible solutions:

- Expose `renderCompleted` externally to be able to determine
- Provide a mechanism to reset `renderCompleted`
- `try ... catch` around at least the `renderFunctions[i]()` and expose the error (e.g. projector.lastError) as well as log it to the console.
- Change the logic to attempt to render anyways.
- Provide a light weight way to register an error listener.

**Comment by johan-gorter** [comment]
What we are always doing is attaching an event listener to the window.onerror, like in the following snippet:

```ts
import {h, dom} from "maquette";

export let handleError = (...args: any[]) => {
  console.error('An error has been reported', ...args);
  dom.append(document.body, h('div.fatal-error', [
    h('span.text', ['Oops, an unexpected error has occurred']),
    h('button.reload', {onclick: () => window.location.reload()}, ['reload'])
  ]));
  debugger
};

window.addEventListener('unhandledrejection', handleError);
window.onerror = handleError;
```

This would catch all errors, not only the ones that occur during rendering. You can also submit the error information (the ...args) to the server (some gotcha's here with serialization of the data).

I am really not a fan of adding a try...catch, because most developer tools halt automatically on uncaught exceptions and not on caught exceptions.

FYI: you can use projector.resume() after it was halted.

**Comment by kitsonk** [comment]
@johan-gorter thanks!  Both of those would work.  Thanks as always.
