### ISSUE TITLE
tabIndex cannot be cleared when using TypeScript

### ISSUE THREAD

**Issue by jcfranco** [AFASSoftware/maquette#81]
According to the [documentation](http://maquettejs.org/docs/rules.html):

> If you render h("div", {tabIndex:"0"}) and then you want to clear the tabIndex attribute, you need to use either h("div", {tabIndex:undefined}), h("div", {tabIndex:null}) or h("div", {tabIndex:""})

Setting `tabIndex` to `undefined` or `null` ends up being cast as 0. Setting an empty string isn't allowed because [`tabIndex` is typed as a number](https://github.com/AFASSoftware/maquette/blob/master/src/maquette.ts#L300). 

Taking code from https://github.com/AFASSoftware/maquette-demo-typescript/blob/master/src/script.ts#L20-L25 as an example:

```tsx
// Renders the whole application
  var renderMaquette = () => {
    const tabIndex = (Math.random() > 0.5) ? null : 0;
    const title = (Math.random() > 0.5) ? null : "title";

    return h("div", [
      textField.renderMaquette(),
      h("p.output", {
        tabIndex,
        title
      }, [("Hello " + (you || "you") + "!")])
    ]);
  }
```

`title` gets cleared, whereas `tabIndex` remains unchanged.

**Comment by johan-gorter** [comment]
I believe there are two problems here:

- The example from the documentation uses the tabIndex **attribute**, whereas we designed the typescript interface to use the tabIndex **property**. These two are magically linked by the DOM implementation of the browser.
- The tabIndex property has a default value for divs of -1. The default value for input elements is 0. Setting the property to *null* magically resets the tabIndex to its default value.

Conclusion: Maquette tries to do the right thing, but the browser magic gets in the way here. We should find a better example for the documentation.

**Comment by johan-gorter** [comment]
I want to use the `target` attribute as in `h('a', {href: '.', target: '_blank'})` in the documentation, this is the most real-world example I can think of where an attribute can be removed.

**Comment by jcfranco** [comment]
👍 

The examples could use spacing for consistency:

`h('a',{href:'.',target:'_blank'})` -> `h('a', {href: '.', target: '_blank'})`

**Comment by johan-gorter** [comment]
I tried with spaces, but then the code wrapped and the readability suffered also. We are reviewing the styling of this page to make it more readable.

**Comment by jcfranco** [comment]
Ah, got it. Thanks for taking care of this! 😄
