### ISSUE TITLE
Referencing DOM nodes on demand

### ISSUE THREAD

**Issue by jcfranco** [AFASSoftware/maquette#85]
What's the recommended approach to referencing DOM nodes on demand (akin to [`refs` in React](https://facebook.github.io/react/docs/refs-and-the-dom.html))? 

In this toy snippet ([codepen here](http://codepen.io/jcfranco/pen/zNvLPe?editors=0011)), the node of interest is stored whenever it is created and referenced afterwards. 

```js
var shared = { node: null };

function focusNode() {
  shared.node.focus();
}  

function storeNode(node) {
  shared.node = node;
}

var form = {
  renderMaquette: function() {
    return h('div', [
      h('textarea', { afterCreate: storeNode }),
      h('button', { onclick: focusNode }, 'focus')
    ]);
  }
};
```

Is this a reasonable pattern or is there a better way?

**Comment by RickHoving** [comment]
That is the way we do things :)
Also note that in most events like the onclick you also can access the DOM nodes.
This is useful when you want to access that particular node, but I think its not useful in your particular example.

**Comment by jcfranco** [comment]
Thanks for the info! It may be worth adding an entry about node-reference patterns to the cookbook.
