### ISSUE TITLE
Maquette Tutorial error

### ISSUE THREAD

**Issue by aMarCruz** [AFASSoftware/maquette#9]
The Maquette tutorial in your website is not working. There are errors in the gutter of HTML frame, in http://maquettejs.org/tutorial/01-intro.html:
```
 Expected an identifier and instead saw '<'.
 ...
```
This is a fragment of error in Chrome console:
```
  MutationObserver fired          workbench.js:120
  http://maquettejs.org/tutorial/bower_components/ace-builds/src-noconflict/mode-html.js  Failed to load resource: the server responded with a status of 404 (Not Found)
```
thanks.

**Comment by johan-gorter** [comment]
Aha, that explains why the css and html are interpreted as javascript. (it worked fine locally)

**Comment by johan-gorter** [comment]
Thanks @aMarCruz for helping out!

**Comment by maccer22** [comment]
Eerste gebruiker :)

Groeten,
Machiel

**Comment by aMarCruz** [comment]
You are welcome @johan-gorter , great work (y).

**Comment by aMarCruz** [comment]
oops! sorry, html nor working yet.
from the Chrome log:
```
GET http://maquettejs.org/tutorial/bower_components/ace-builds/src-noconflict/worker-html.js 404 (Not Found)
    WorkerClient | @ ace.js:16106
    createWorker | @ mode-html.js:2416
    $startWorker | @ ace.js:8626
    $onChangeMode | @ ace.js:8582
    (anonymous function) | @ ace.js:8563
    (anonymous function) | @ ace.js:3629
    (anonymous function) | @ ace.js:3628
    _require | @ ace.js:88
    req | @ ace.js:138
    exports.loadModule.afterLoad | @ ace.js:3624
    exports.loadScript.s.onload.s.onreadystatechange | @ ace.js:3270
```

**Comment by johan-gorter** [comment]
I added worker-html.js as well. I have never seen this error message, so I wonder what you did and what browser you used.

**Comment by aMarCruz** [comment]
mmm... the error is gone, but I can't edit the html, the frame is read-only.
I'm using Windows 7, 32 bits, testing with Chrome 42.0.231190, Firefox 37.0.2, 

Wait... its working in IE 11.0.9600.17728 and Maxthon 4.4.4.2000 !
(Maxthon is an excelent webkit compatible browser)

**Comment by aMarCruz** [comment]
The HTML/CSS looks ok
![_captura1](https://cloud.githubusercontent.com/assets/6636980/7335467/5b6fce34-eb88-11e4-9a09-9ccb6453d720.png)

something in the js code is eathing keystrokes?
...

**Comment by aMarCruz** [comment]
I got it !!!
the bad guy is Adblock Plus. I deactivate this and now is working, Chrome and FF !!
anyway..., interesting problem. Adblock Plus is the **must used** extension in this browsers.
